/* ANILyfe checkout — records a read-only local order snapshot until backend/payment integration is connected. */
function viewCheckout(){
  const u=currentUser(); if(!u){location.hash='#/auth';return '';}
  const state=u.state||u.location?.state||''; const totals=getCartTotals(state);
  const states=(typeof NIGERIAN_STATES_SHARED!=='undefined'?NIGERIAN_STATES_SHARED:[]);
  return `<div class="min-h-screen" style="background:var(--off)"><header class="max-w-3xl mx-auto px-5 py-5 flex items-center justify-between">${LOGO('text-2xl')}<a href="#/cart" class="btn btn-ghost text-xs">← Back to cart</a></header><main class="max-w-2xl mx-auto px-5 pb-24"><h1 class="font-display text-2xl font-extrabold mb-6">Checkout</h1><div class="card p-6 space-y-5"><div><div class="font-display font-bold">Delivery information</div><p class="text-xs text-slate-500 mt-1">Select the Nigerian state for this delivery. Shipping is recalculated from this selection.</p><div class="grid sm:grid-cols-2 gap-3 mt-4"><div><label class="lbl">Country</label><input class="inp" value="Nigeria" readonly></div><div><label class="lbl">State *</label><select class="inp" id="checkoutState" required>${states.map(st=>`<option value="${esc(st)}" ${st===state?'selected':''}>${esc(st)}</option>`).join('')}</select></div><div><label class="lbl">City / Town *</label><input class="inp" id="checkoutCity" value="${esc(u.city||u.location?.city||'')}" required></div><div><label class="lbl">LGA / Area</label><input class="inp" id="checkoutLga" value="${esc(u.lga||u.location?.lga||'')}"></div><div class="sm:col-span-2"><label class="lbl">Delivery address *</label><textarea class="inp min-h-[90px]" id="checkoutAddress" required>${esc(u.address||'')}</textarea></div></div></div><div class="border-t pt-4 space-y-2"><div class="flex justify-between text-sm"><span>Subtotal</span><b>${fmt(totals.subtotal)}</b></div><div class="flex justify-between text-sm"><span>Shipping</span><b>${fmt(totals.shipping)}</b></div><div class="flex justify-between font-display font-extrabold text-lg"><span>Total</span><span>${fmt(totals.total)}</span></div></div><p class="text-xs text-slate-500">Payment processing will be connected to Paystack/backend services. This front-end records the order as pending payment.</p><button class="btn btn-primary w-full" data-action="checkout">Place order</button></div></main></div>`;
}
function checkoutNow(){
  const u=currentUser(); if(!u){location.hash='#/auth';return;}
  const state=document.getElementById('checkoutState')?.value||''; const city=document.getElementById('checkoutCity')?.value.trim()||''; const lga=document.getElementById('checkoutLga')?.value.trim()||''; const address=document.getElementById('checkoutAddress')?.value.trim()||'';
  if(!state||!city||!address){toast('Complete the delivery state, city and address.','map-pin');return;}
  const totals=getCartTotals(state); if(!totals.items.length){toast('Your cart is empty.','shopping-cart');location.hash='#/cart';return;}
  const orders=LS.get('orders',[]), groups=new Map(), created=[];
  totals.items.forEach(x=>{const a=groups.get(x.product.sellerId)||[];a.push(x);groups.set(x.product.sellerId,a);});
  for(const [sellerId,items] of groups){
    const seller=LS.get('sellers',[]).find(s=>s.id===sellerId); const ship=totals.shippingBreakdown.find(x=>x.sellerId===sellerId)?.fee||0; const subtotal=items.reduce((n,x)=>n+x.lineTotal,0); const rate=Number(LS.get('marketplaceSettings',{}).commission??15); const commission=Math.round(subtotal*rate/100); const now=new Date().toISOString();
    const order={id:uid('ORD'),buyerId:u.id,buyer:{id:u.id,name:u.name,email:u.email,phone:u.phone||'',country:'Nigeria',state,city,lga,address},sellerId,sellerName:seller?.businessName||seller?.storeName||'Seller',country:'Nigeria',deliveryLocation:{country:'Nigeria',state,city,lga,address},items:items.map(x=>({productId:x.product.id,productName:x.product.name,productImage:x.product.img||(x.product.images||[])[0]||null,sku:x.product.sku||'',quantity:x.qty,unitPrice:x.unit,lineTotal:x.lineTotal})),subtotal,shippingFee:ship,shipping:ship,marketplaceCommission:commission,commissionAmount:commission,commissionRate:rate,sellerEarnings:Math.max(0,subtotal-commission),total:subtotal+ship,paymentStatus:'Pending Payment',orderStatus:'New',status:'New',createdAt:now,timeline:[{status:'New',timestamp:now,note:'Order recorded; awaiting payment processing.'}]};
    orders.push(order);created.push(order);
  }
  LS.set('orders',orders); localStorage.setItem('anilyfe_seller_orders',JSON.stringify(orders)); LS.set('cart',[]);
  created.forEach(o=>window.adminNotificationService?.add({type:'new_order',title:'New order received',message:`${o.sellerName} · ${fmt(o.total)}`,orderId:o.id,sellerId:o.sellerId}));
  toast(`${created.length} order${created.length===1?'':'s'} recorded.`,'badge-check'); location.hash='#/orders';
}
